theme: jekyll-theme-cayman
title: Navega Tranquilo, Navega Feliz
description: Más seguro, más rápido, mejor en todos los aspectos. Actualiza tu navegador hoy. Vinculos con descargas para navegadores modernos, para que usuarios anclados en IE encuentren una vía de escape
